ExamenPublicaciones/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('registro/', views.registro,name='registro'),
    path('inicio/',views.iniciar,name='login'),
    path('publicaciones/',include('Publicaciones.urls')),
]

Publicaciones/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = "Publicaciones" 

urlpatterns = [
    path('', views.index, name='index'),
    re_path('(?P<slug>[\w-]+)/$', views.publicacion, name='publicacion'),
]

Publicaciones/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Usuario(User):
    nombre = models.CharField(max_length=40,null=False)
    paterno = models.CharField(max_length=40,null=False)
    materno = models.CharField(max_length=40,null=False)

    def __str__(self):
        return self.nombre + " " + self.paterno + " " + self.materno 

class Categoria(models.Model):
    categoria = models.CharField(max_length=50)

    def __str__(self):
        return self.categoria

class Publicacione(models.Model):
    titulo = models.CharField(max_length=50)
    cuerpo = models.TextField(max_length=900)
    slug = models.CharField(max_length=50,null=False)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

Publicaciones/forms.py
from django import forms
from .models import *
import datetime
from django.utils import timezone
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('username','password','nombre','paterno','materno',)
        labels = {
            'username': ('Introduzca su nombre de usuario'),
            'password': ('Introduzca su contraseña'),
            'nombre': ('Introduzca su nombre(s)'),
            'paterno': ('Introduzca su apellido paterno'),
            'materno': ('Introduzca su apellido materno'),
        }
        widgets = {
            'username': forms.TextInput(attrs={'id':'usuario', 'class':'validate'}),
            'password': forms.PasswordInput(attrs={'id':'password', 'class':'validate'}),
            'nombre': forms.TextInput(attrs={'id':'nombre', 'class':'validate'}),
            'paterno': forms.TextInput(attrs={'id':'paterno', 'class':'validate'}),
            'materno': forms.TextInput(attrs={'id':'materno', 'class':'validate'}),
        }

class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacione
        fields = ('titulo','cuerpo','categoria','slug',)
        labels = {
            'titulo': ('Introduzca el titulo'),
            'cuerpo': ('Introduzca el articulo'),
            'categoria': ('Seleccione una categoría'),
            'slug': ('Introduzca la dirección del articulo'),
        }
        widgets = {
            'titulo': forms.TextInput(attrs={'id':'titulo', 'class':'validate'}),
            'cuerpo': forms.TextInput(attrs={'id':'cuerpo', 'class':'validate'}),
            'slug': forms.TextInput(attrs={'id':'slug', 'class':'validate'}),
        }

class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'id':'usuario', 'class':'validate'})),
    password = forms.CharField(widget=PasswordInput(attrs={'id':'password', 'class': 'validate'})),

ExamenPublicaciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from Publicaciones.forms import *

def index(request):
    return render(request,'index.html')

def iniciar(request):
    if request.method == 'POST':
        form = CustomAuthForm(data=request.POST)
        if form.is_valid():
            usuario = form.get_user()
            login(request,usuario)
            return redirect('Publicaciones:index')
    else:
        form = CustomAuthForm()
    return render(request,'login.html',{'form':form})

def registro(request):
    registered = False
    if request.method == 'POST':
        form = UsuarioForm(data=request.POST)
        if form.is_valid():
            form = form.save()
            form.set_password(form.password)
            form.save()
            registered = True
            return redirect('Publicaciones:index')
    else:
        form = UsuarioForm()
    return render(request,'registro.html',{'form':form})

def salir(request):
	if request.method=='POST':
		logout(request)
		return redirect('index')

Publicaciones/views.py
from django.shortcuts import render
from .models import *

def index(request):
    publicaciones = Publicacione.objects.all()
    return render(request,'Publicaciones/index.html',{'publicaciones':publicaciones})


def publicacion(request, slug):
    pub = Publicacione.objects.get(slug=slug) 
    return render(request,'Publicaciones/publicaciones.html',{'pub':pub})

Publicaciones/templates/Publicaciones/base.html
{% load static from staticfiles %}
<HTML>
	<head>
		<meta charset="utf-8">
        <title>Publicaciones cientificas</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'Estilos/estilos.css' %}">
		</head>		
		<body class="fondo-principal">
            <div class="fondo-secundario">
                    <nav>
                        <div class="nav-wrapper">
                              <a href="{% url 'index' %}" class="brand-logo">Ir al menú</a>
                              <ul id="nav-mobile" class="right hide-on-med-and-down">
                                <li><a href="{% url 'registro' %}"><i class="material-icons left">person_add</i>Registrarme</a></li>
                                <li><a href="{% url 'login' %}"><i class="material-icons left">person</i>Iniciar Sesion</a></li>
                                <li><a href="{% url 'Publicaciones:index' %}"><i class="material-icons left">book</i>Ir a Publicaciones</a></li>
                              </ul>
                            </div>
                          </nav>
                {% block contenido %}
                {% endblock %}
            </div>
        </body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</HTML>

Publicaciones/templates/Publicaciones/index.html
{% extends 'Publicaciones/base.html' %}

{% block contenido %}

{% for publicacion in publicaciones %}

<div class="fondo-login">
    <a href="{% url 'Publicaciones:publicacion' slug=publicacion.slug %}">{{publicacion.titulo}}</a><br>
</div>
{% endfor %}

{% endblock %}

Publicaciones/templates/Publicaciones/publicaciones.html
{% extends 'Publicaciones/base.html' %}

{% block contenido %}

<div class="fondo-login">
       <h4>Articulo escrito por: {{pub.autor}}</h4><br>

        <h5>{{pub.titulo}}</h5><br>
        <p>{{pub.cuerpo}}</p>
</div>

{% endblock %}

templates/base.html
{% load static from staticfiles %}
<HTML>
	<head>
		<meta charset="utf-8">
        <title>Publicaciones cientificas</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'Estilos/estilos.css' %}">
		</head>		
		<body class="fondo-principal">
            <div class="fondo-secundario">
                    <nav>
                        <div class="nav-wrapper">
                              <a href="{% url 'index' %}" class="brand-logo">Ir al menú</a>
                              <ul id="nav-mobile" class="right hide-on-med-and-down">
                                <li><a href="{% url 'registro' %}"><i class="material-icons left">person_add</i>Registrarme</a></li>
                                <li><a href="{% url 'login' %}"><i class="material-icons left">person</i>Iniciar Sesion</a></li>
                                <li><a href="{% url 'Publicaciones:index' %}"><i class="material-icons left">book</i>Ir a Publicaciones</a></li>
                              </ul>
                            </div>
                          </nav>
                {% block contenido %}
                {% endblock %}
            </div>
        </body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</HTML>

templates/index.html
{% extends 'base.html' %}

{% block contenido %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block contenido %}

<div class="fondo-login">
    <div class="fondo2-login"><h3>Ingrese sus datos de usuario
<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <div class="input-field col s6">
        {{form.username}}<br><br>
        <label for = "usuario">{{form.username.label}}</label>
    </div>

    <div class="input-field">
        {{form.password}}<br><br>
        <label for="password">{{form.password.label}}</label>
    </div>
<button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
</button>

</form>
</div>

</div>

{% endblock %}

templates/registro.html
{% extends 'base.html' %}

{% block contenido %}

<div class="fondo-registro">
        <div class="fondo2-registro"><h3>Registrar datos de usuario
    <form action="{% url 'registro' %}" method="POST">
        {% csrf_token %}
        <div class="input-field col s6">
            {{form.username}}<br>
            <label for = "usuario">{{form.username.label}}</label>
        </div>
    
        <div class="input-field">
            {{form.password}}<br>
            <label for="password">{{form.password.label}}</label>
        </div>

        <div class="input-field">
            {{form.nombre}}<br>
            <label for="nombre">{{form.nombre.label}}</label>
        </div>

        <div class="input-field">
            {{form.paterno}}<br>
            <label for="paterno">{{form.paterno.label}}</label>
        </div>

        <div class="input-field">
            {{form.materno}}<br>
            <label for="materno">{{form.materno.label}}</label>
        </div>

    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
    </button>
    
    </form>
    </div>
    
    </div>

{% endblock %}